### ISSUE TITLE
Problem with composing classes

### ISSUE THREAD

**Issue by j-panasiuk** [mdgriffith/style-elements#1]
First, let me say I really like the approach you have taken with this library! If we are pre-processing css anyway, it may be a good idea to add some sanity along the way :)

One thing I'm struggling with, is how to get small "utility" classes to work. These could be things like adding small style modification to active UI element
```css
.active { color: green; }
```
If I try to define such helper class
```elm
class Active [ textColor Color.green ]
```
it always comes together with base styles
```
.active-eabjjaciej {
  box-sizing: border-box;
  display: block;
  top: 0px;
  left: 0px;
  position: relative;
  color: rgba(115,210,22,1);
}
```
which (depending on display and position) sometimes messes up positioning.

What I tried to do is
1) trim/remove Style.base
2) move the class to separate stylesheet
but in both cases these base styles still get attached to my class and it's not clear to me where this inheritance happens

Is there a simple way to get the banana without the gorilla here? :)

**Comment by j-panasiuk** [comment]
Also, as a follow up question: what about applying styles when element has 2+ classes?
```css
.foo.bar { color: green; }
```
Or is this not a thing?

**Comment by mdgriffith** [comment]
Hello!  I'm glad you appreciate the library, and I really appreciate the feedback :)

Actually this is something I've been thinking about.  I've been debating adding a `decoration` function which would be just like `class` but skip all the properties from `base`...we'll see if that happens, but I'm definitely thinking about it.

In the meantime, one way to approach this is to have `Active` have all the properties of the class it's replacing.  You can do this by creating the style outside of the stylesheet and then applying it in the places it's needed.

Let's say you're styling an input button.

```elm
button = 
   [ positionBy screen
   , topLeft 0 25
   ]


stylesheet =
    Style.render
         [ class Button
                button
         , class Active
                [ Style.mix button
                , textColor Color.green
                ]
         ]
```

Second point, yes, you can definitely use multiple, separate styles.  You just have to use `classList`.

So It'll look something like this:
`stylesheet.classList [(Foo, True), (Bar, True)]`

**Comment by j-panasiuk** [comment]
This works, thanks!

On the other hand it's not great, because now I have `Active` class tightly coupled to `Button`. If I define `Active` multiple times in one stylesheet, each instance gets its own hashed css class... but then view code only knows about the first one anyway. So to reuse `Active` in a different context, I have to move it to different stylesheet. Which kind of works, but feels clunky.

Alternatively I can drop the idea of gluing two classes together like `.button.active` and just stick to individually namespacing things like `ButtonActive`. That may be simplest way to go actually... the downside is classes will then start multiplying like rabbits, but for a small app it shouldn't be that bad.

An idea I just had was "wouldn't it be nice if inside stylesheet I had function exactly like **class**, but accepting 2 types". So in this case instead of
```elm
Style.render
    [ class Button
        button
    , class Active
        [ Style.mix button
        , textColor Color.green
        ]
    ]
```
I could pass `Active` as parameter
```elm
Style.render
    [ class Button
        button
    , class2 Button Active
        [ Style.mix button
        , textColor Color.green
        ]
    ]
```
and get **button-active-12356343** class generated. I know class2 is not prettiest, but the idea is to generate single css name representing element + modifiers and keep types reusable on elm side. Maybe even something like
```elm
classes : Set class -> List Property -> Model class
```
Though that will look silly until sets get their own syntax (which I hope *eventually* happens...)

Anyway, looking forward to further developments! :)

**Comment by mdgriffith** [comment]
I like your `class2` example.  I'll give it some thought as I consider the options for this use-case.

Currently I'm playing around with something like the following:

```elm
Style.render
    [ class Button
        [ positionBy screen
        , topLeft 0 25
        , variation Active
               [ textColor Color.green ]  
        ]
    ]
```

Though the immediate question here is "Is Button and Active the same type"?  What happens when you just render something as `Active` but not `Button`?

I can pretty easily log warnings at runtime, but catching all that stuff at compiletime would be really nice.
