### ISSUE TITLE
`shadows` property no longer works

### ISSUE THREAD

**Issue by mrvicadai** [mdgriffith/style-elements#100]
## The big picture of what I'm trying to do

Make a box shadow with a list of `Shadow.box` properties that adheres to Google Material Design.

## What I did

While using `3.4.1` I was able to do:

```
            shadows
                [ Shadow.box
                    { offset = ( 0, 14 )
                    , size = 0
                    , blur = 45
                    , color = Color.rgba 0 0 0 0.25
                    }
                , Shadow.box
                    { offset = ( 0, 10 )
                    , size = 0
                    , blur = 18
                    , color = Color.rgba 0 0 0 0.22
                    }
                ]
```

However, after upgrading to 4.1.0, the `shadows` function is no longer exposed.

### What I Expected To Happen

`Internal.Shadows` or `shadows` method is exposed to the users who would like to make complex shadows.

### What Actually Happened

After upgrading to 4.1.0, the `shadows` function is no longer exposed.

## Versions

- Elm: 0.18 
- style-elements: 4.1.0 
- Browser: Safari 
- Operating System: macOS High Sierra

**Comment by mdgriffith** [comment]
`Shadow.box` and other shadows can now be used directly in the style and they will stack in the order that they are given.  So, you should be able to do any complex shadows you need to do, just bring them down a level :)

**Comment by mrvicadai** [comment]
Oh sweet! This actually sounds much better compared to the older API. Thanks!
