### ISSUE TITLE
select/dropDown problems: autoclose on first click, ghost click

### ISSUE THREAD

**Issue by Augustin82** [mdgriffith/style-elements#107]
## The big picture of what I'm trying to do

Use a select with a dropdow menu and several options.

## What I did

The following Ellie:
https://ellie-app.com/cVxGzYRWBa1/6

### What I Expected To Happen

I expected it to behave similarly to a regular select: open when I click, close when I select, open when I click again, etc.

### What Actually Happened

There are two problems happening:
1) when I first click on the dropdown, it rapidly opens/closes. It's only the second click that allows me to pick an option
2) after selecting an option, the dropdown remains "focused". If at that moment, without doing anything else, I click once in another window, and then click again somewhere in the HTML section of the Ellie, the dropdown will open/close rapidly again.

## Versions

- Elm: 0.18
- style-elements: 4.2.0
- Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)
- Browser: Firefox 56.0 (64-bit)
- Operating System: Ubuntu 16.04.3 LTS 64-bit

**Comment by alvivi** [comment]
I'm having the same problem, but only with a MacBook and using the trackpad. If I use a single "soft" tap, it works. But if I click on the trackpad, the drop menu hides instantly. 

Maybe a good solution is avoid closing the menu when the user clicks on the selected element, so the second click does nothing.

**Comment by kuon** [comment]
I just hit this issue using firefox 57 under windows 10. It makes the menu unusable so far.

**Comment by pro100filipp** [comment]
Submitted a pull request, @mdgriffith could you please merge it? I think it's rather annoying bug but don't want to pollute http://package.elm-lang.org with hard fork 😃
