### ISSUE TITLE
Replace CSS reset with a modern one (or even a custom one + Normalize.css)

### ISSUE THREAD

**Issue by Dremora** [mdgriffith/style-elements#11]
Normalize.css is a well-maintained library providing de-facto normalization of default styles between browsers. We probably do want to go extra step and reset those paddings, margins, font sizes and line-heights. I'm not sure why `vertical-align` has the value of `baseline;`, though.

**Comment by mdgriffith** [comment]
Good call.  I put together a combination of [normalize.css v7.0 and the padding/margin/fontsize/lineheight/borderwidth resets](https://github.com/mdgriffith/style-elements/blob/master/references/modified-normalize.css).

The elm code contains a minified version of that file.
