### ISSUE TITLE
Checkbox API is not the same as for other input elements

### ISSUE THREAD

**Issue by kuzzmi** [mdgriffith/style-elements#12]
Not sure if this is something that should be improved, but probably this will lead to more flexible use.

```
checkbox
    :  Bool
    -> style
    -> List (Attribute variation msg)
    -> Element style variation msg
    -> Element style variation msg

inputText
    :  style
    -> List (Attribute variation msg)
    -> String
    -> Element style variation msg
```

In this case it's quite problematic to make something like this:

```
input inputElement label_ value = 
    label None [] (text label_) <| 
        inputElement TextInputStyle [ paddingXY 0 5 ] value

...
[ input inputText "Title" post.title
, input textArea "Description" post.description
, input checkbox "Published?" post.isPublished
]
...
```

**Comment by rtfeldman** [comment]
> In this case it's quite problematic to make something like this

It doesn't have to be! You can make a union type for the different situations:

```elm
[ input (Text "Title" post.title)
, input (TextArea "Description" post.description)
, input (Checkbox "Published?" post.isPublished)
]
```

Then run a _case-expression_ on each constructor and call the appropriate function. Voila!

> Checkbox API is not the same as for other input elements

I think it's very important that this continue to be true.

Checkboxes are different than other input elements, and if they all have the same API, I think something has gone very wrong! 😄

**Comment by kuzzmi** [comment]
Good catch @rtfeldman, this absolutely makes sense. 

However, what I was referring to is basically that the API of inputs is not aligned

```
checkbox: Value -> Style -> Attributes -> Content -> Element
inputText: Style -> Attributes -> Value -> Element
textArea: Style -> Attributes -> Value -> Element
select: Name -> Style -> Attributes -> "Values" -> Element
...
```

Doesn't it make sense to align them together as much as possible, does it?

```
checkbox: Style -> Attributes -> Value -> Content -> Element
inputText: Style -> Attributes -> Value -> Element
textArea: Style -> Attributes -> Value -> Element
select: Style -> Attributes -> "Values" -> Name -> Element
```

**Comment by mdgriffith** [comment]
Input elements got a huge overhaul in `v4.0.0`.  They're way different, but hopefully address the consistency and concerns of inputs a bit better.  Thanks for the issue!
