### ISSUE TITLE
Typo in Docs/GitBook Style.syleSheet should be Style.styleSheet

### ISSUE THREAD

**Issue by nelsonic** [mdgriffith/style-elements#123]
Hi @mdgriffith love your work!
_Excited_ to be using `style-elements` for a _client_ project!

Just wanted to report a minor typo in https://www.gitbook.com/book/mdgriffith/style-elements/details
![image](https://user-images.githubusercontent.com/194400/33516774-3fd5e164-d770-11e7-9528-deb726039dd3.png)

and https://mdgriffith.gitbooks.io/style-elements/content/defining-a-stylesheet.html
![image](https://user-images.githubusercontent.com/194400/33516765-2395f20a-d770-11e7-8208-d97917eef50b.png)

Happy to PR a fix, but could not find the _source_ of the Guide on GitHub ... 

## Versions

- Elm: 0.18
- style-elements: 4.2.1 (_note: issue is not specific to the library, rather to the docs/guide_)
- Browser: Any/All
- Operating System: Any/All

**Comment by mdgriffith** [comment]
Thanks!  I've fixed it.

(And super excited you're using style-elements for a client project!)

**Comment by nelsonic** [comment]
@mdgriffith sweet. thanks! will report progress once we _ship_ the app! 😉
