### ISSUE TITLE
How to compose across modules?

### ISSUE THREAD

**Issue by amitu** [mdgriffith/style-elements#13]
I have two modules, Header and Dashboard, and I can compose their HTML msg-es in my Main, by using `Html.map DashboardMsg` etc.

What I want is: change the signature of my Dashboard.view/Header.view etc to return Element.Element instead of Html.Html, but how do I compose them in my Main.view?

What works so far is return Html from Dashboard.view by calling Element.render, and then calling Element.html to re-wrap into Element so my overall layout works.

**Comment by amitu** [comment]
Other alternative is to send a tagger from Main.view to Dashboard.view.

**Comment by mdgriffith** [comment]
This is definitely an oversight.  I've put this on the [map for `v3.1`](https://github.com/mdgriffith/style-elements/issues/14)

**Comment by amitu** [comment]
Cool, will close this one. The tagger approach works for me.
