### ISSUE TITLE
Bugs/Features for 3.1

### ISSUE THREAD

**Issue by mdgriffith** [mdgriffith/style-elements#14]
- [x] replace reset.css with normalize.css
 - [x] `Element.map` is missing and necessary
 - [x] adjust css to allow fullscreen apps
 - [x] flex-shrink 0
 - [x] add overflow properties on `Elements`
 - [x] pseudo-class in variation that's turned off should not apply
 - [x]  `link "test"` on a layout el doesn't register properly. 
 - [x] Basic testing suite using `elm-html-test`
 - [x] row layout, child with height (fill 1) renders as `height: 100%`, but does not actually grow to 100%;

**Comment by amitu** [comment]
inputText should take type as input, instead of hardcoding it. No way to create password field as of now (AFAIK). Other alternative is to give a inputPassword, inputDate, inputEmail and so on (not too big a list as there are only few types).

**Comment by mdgriffith** [comment]
You can create custom elements right now by doing something like:

`node "input" <| el Style [ type_ "password" ] empty`

Though I like the idea of having more form nodes covered directly.
