### ISSUE TITLE
0.19 Support?

### ISSUE THREAD

**Issue by bstro** [mdgriffith/style-elements#154]
Will style-elements be receiving support for Elm 0.19?
Currently, when attempting to `elm install` this package, I receive `The following packages do not work with Elm 0.19.0 right now: mdgriffith/style-elements`

**Comment by mdgriffith** [comment]
Yes, there will be `0.19` support, I'm planning to do the release later today.

**Comment by mdgriffith** [comment]
Looks like I'm waiting for at least one upstream package.  Once that's out, there's still at least one small part of the code that needs to be rewritten.

So, it might not be upgraded today, but it will sometime soon :)

**Comment by bstro** [comment]
Awesome thanks !!!!!!
