### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by paulbellamy** [mdgriffith/style-elements#17]
In the responsive section of Element, it says "Check out the <a href="https://github.com/mdgriffith/elm.style">elm.style website source</a> for a real example.", but that link 404s.

**Comment by mdgriffith** [comment]
Whoops, I haven't published that yet.  The elm.style website should be put together in the next week or so and I'll publish the code then as well.

**Comment by nelsonic** [comment]
still `404`. let us know if you need _any_ help. 
we are v. keen to use this lib in our next elm project (_starting in a couple of days time..._) 
keen to help with docs wherever possible. 
e.g: https://github.com/dwyl/learn-tachyons

**Comment by mdgriffith** [comment]
I forgot to update this issue when the plan changed :)

The elm.style website took a backseat while I've been working on `v5`.  Once `v5` is released, I'll return to it.

I appreciate the offer for help!  I'll definitely keep that in mind, especially as I finish up `v5`.

I'm going to close this issue.  The `elm.style` website will be announced on a larger platform when it's ready.
