### ISSUE TITLE
Additional Style Properties

### ISSUE THREAD

**Issue by mdgriffith** [mdgriffith/style-elements#2]
This issue is for listing and discussing adding support for new properties for this library.  If you think this library should support a css property, leave a comment!

Currently suggested

- [ ] [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)

**Comment by j-panasiuk** [comment]
I noticed `list-style` isn't currently supported https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
Actually I think most of the options are silly, I just wanted to use `list-style-type: "none"`

**Comment by j-panasiuk** [comment]
Also `pointer-events` https://css-tricks.com/almanac/properties/p/pointer-events/

I only recently discovered this property and it turned out to be super helpful. It solves typical z-index problems, where mouse events are swallowed by the topmost layer, but we want it to propagate down

**Comment by mdgriffith** [comment]
Background-size, requested in issue https://github.com/mdgriffith/style-elements/issues/6

**Comment by mdgriffith** [comment]
I'm closing this issue because this library has changed dramatically since I this happened.  If you find a property you'd like to use that's not here, file a new issue :)
