### ISSUE TITLE
onSubmit for form

### ISSUE THREAD

**Issue by amitu** [mdgriffith/style-elements#20]
I see that `form` converts an element to another, e.g. a column to form. In this case, where do I specify onSubmit event handler. Putting it on column seems wrong, and form doesn't take any inputs. Should it take a list of extra attributes?

**Comment by mdgriffith** [comment]
It goes on the column element.  It may feel weird but it's correct. 

In some cases I've been toying with having a mandatory attribute for some input elements (such as how it's done with the `checkbox` element), but I'm also hesitant to do that too much.  So, we'll see.
