### ISSUE TITLE
minHeight?

### ISSUE THREAD

**Issue by amitu** [mdgriffith/style-elements#21]
I have a bunch of pages, and I want the footer to stick to bottom. I tried putting height = 100% and enabling scrollbars, but Element.column seems to be wrapping them weirdly. Wrapping gets fixed if I remove height, but then footer is in the middle of the page. 

PS: I am hoping GitHub issues for clarifications are okay. Do let me know if you prefer such beginner questions in slack etc.

**Comment by amitu** [comment]
Closing in favour of #22.

**Comment by mdgriffith** [comment]
Saw you just closed this, but wanted to say thanks for asking!  I would say let's keep question in slack and have the github issues be for unexpected behavior/bugs.  I've added min/max height on the list for v3.2.

**Comment by amitu** [comment]
Got it.
