### ISSUE TITLE
Percentage border radius

### ISSUE THREAD

**Issue by opsb** [mdgriffith/style-elements#24]
I often use this when I want to make images circular e.g.

```
<img src="http://avatars.com/40/jimbo.jpg" style="border-radius: 50%"> 
```

I'm using the `prop` escape hatch for now, `prop "border-radius" "50%"`, but what are your thoughts on allowing different units for `Border.rounded`?

* `Border.rounded (percentage 50)`
* `Border.rounded (px 50)`

**Comment by mdgriffith** [comment]
There's an `Element.circle` constructor, does that solve your case?

**Comment by opsb** [comment]
`Element.circle` still takes a pixel size, it also doesn't have `overflow: hidden` set so it doesn't clip the image. For context I did

```
avatar =
    circle 50
        None
        []
        (image "http://i.pravatar.cc/30"
            Avatar
            [ width (px 30)
            , height (px 30)
            ]
            empty
        )
```

**Comment by mdgriffith** [comment]
So, just to get my understanding correct, you want the circle to be it's natural width and height, but a circle and `border-radius: 50%` does that, right?

And we do need `overflow: hidden`.  I'm sorta toying with the name `clipped`.

**Comment by opsb** [comment]
> but a circle and border-radius: 50% does that, right?

yes I think that would do it.

> I'm sorta toying with the name clipped.

I like `clipped`. I was thinking `mask` but that implies that it isn't visible and perhaps you add a border etc.
