### ISSUE TITLE
Sending row element into a link function does not always apply href in anchor tag

### ISSUE THREAD

**Issue by Oustad** [mdgriffith/style-elements#27]
The example code underneath does not produce a href attribute in the anchor tag.

` link (Route.routeToString Route.Home) <|  row SideBarElement
            [ width <| fill 1, padding 20, verticalCenter, spacing 20 ]
            [ (node "i" <| el SideBarElementIcon [ class "fa fa-home" ] empty), (el None [ paddingTop 5 ] (text "Home")) ] `

Though by simply removing the spacing 20, the href attribute is added to the anchor tag, the other layout attributes doesn't seem to affect the issue.

` link (Route.routeToString Route.Home) <|  row SideBarElement
            [ width <| fill 1, padding 20, verticalCenter ]
            [ (node "i" <| el SideBarElementIcon [ class "fa fa-home" ] empty), (el None [ paddingTop 5 ] (text "Home")) ] `

**Comment by mdgriffith** [comment]
Fixed in `v3.2`!
