### ISSUE TITLE
Parentheses are not allowed in class names

### ISSUE THREAD

**Issue by BrianHicks** [mdgriffith/style-elements#30]
When you have a sub style with a parameter inside a parent style, `style-elements` generates class names with parentheses in them (I assume as an artifact of using `toString` somewhere?) Parentheses aren't valid in class names, so the browser fails to style the elements.

[SSCCE in an Ellie](https://ellie-app.com/3yttdHNhgGKa1/0)

SSCCE as code:

```elm
module Main exposing (..)

import Element exposing (..)
import Style exposing (..)
import Style.Font as Font


type Super
    = None
    | DecoratedText Text


type Text
    = Plain
    | Emphasis Int


sheet =
    Style.stylesheet
        [ style None []
        , style (DecoratedText Plain) []
        , style (DecoratedText <| Emphasis 1) [ Font.italic ]
        , style (DecoratedText <| Emphasis 2) [ Font.bold ]
        ]


main =
    viewport sheet <|
        column None
            []
            [ el (DecoratedText Plain) [] (text "Undecorated")
            , el (DecoratedText <| Emphasis 1) [] (text "Italic")
            , el (DecoratedText <| Emphasis 2) [] (text "Bold")
            ]

```

My ultimate goal that lead to this situation: wrap a markdown parser's output in `Element`s so that you can control styling of each generated element. I've worked around it for now by using `Emphasized` and `StronglyEmphasized` instead of `Emphasis Int`.

**Comment by mdgriffith** [comment]
Fixed in `v3.2`~
