### ISSUE TITLE
`width fill` should set flex-basis:0

### ISSUE THREAD

**Issue by avh4** [mdgriffith/style-elements#36]
In the following example, having rows with elements of `width (fill 1)` causes the resulting widths to depend on the length of text in each element instead of evenly distributing the width.

The fix for this would be to add `flex-basis: 0` to such elements.

https://ellie-app.com/3FtPh8xDBhBa1/0

```elm
    column () []
        [ row () []
            [ el () [ width <| fill 1 ] (text ".")
            , el () [ width <| fill 1 ] (text "short")
            ]
        , row () []
            [ el () [ width <| fill 1 ] (text "short")
            , el () [ width <| fill 1 ] (text "looooooooong")
            ]
        ]
```

Current:
<img width="400" alt="screen shot 2017-07-04 at 1 03 18 pm" src="https://user-images.githubusercontent.com/1222/27841810-2ee31076-60b9-11e7-93a8-7c1cabc9d74e.png">

With `flex-basis: 0` manually added to the els:
<img width="400" alt="screen shot 2017-07-04 at 1 03 03 pm" src="https://user-images.githubusercontent.com/1222/27841825-3f865992-60b9-11e7-8028-329e3f099595.png">

**Comment by mdgriffith** [comment]
v4.0.0 switches the flex-basis to 0, thanks Aaron!
