### ISSUE TITLE
unable to build a password input from inputText

### ISSUE THREAD

**Issue by roovo** [mdgriffith/style-elements#37]
using:

```elm
inputText None [ type_ "password" ] "secret"
```

results in an input with the type set to "text" so that the word "secret" is visible.  Looks like the ordering that the attrs is built in inputText (or I guess consumed) results in the default value taking precedence.

I'm having to fall back to using

```elm
node "input" <| el None [ type_ "password", value "secret" ] empty
```

so it's not a blocker but I presume the intent was for this to be over-ridable.

Thanks for building this btw - it was your elm europe talk that got me looking at it and I'm loving it so far.

**Comment by mdgriffith** [comment]
v4.0.0 introduces password inputs!  Thanks for the issue :)

**Comment by mdgriffith** [comment]
(and thanks for enjoying the library, I hope it continues to be an awesome experience )
