### ISSUE TITLE
alingTop does not seem to flex-start

### ISSUE THREAD

**Issue by Rolograaf** [mdgriffith/style-elements#4]
In my opinion CSS debugging -- in an elm app -- is not a very straightforward job. 

I use the CSS from [an example in elm for dropdowns](https://github.com/wintvelt/elm-dropdown) and try to convert it to `style-elements`. I really like the concept of `alingTop` which should `align-items flex-start` and thus float the items to the top. I tried it on [flexbox playground](https://demos.scotch.io/visual-guide-to-css3-flexbox-flexbox-playground/demos/ )

With trial and error I got most of it fixed, but still the other dropbox will fall to the bottom when a dropbox is rolled-down using `alingTop` to container and/or to the element itself.

![stand_20161231](https://cloud.githubusercontent.com/assets/6130902/21741778/f8583fc2-d4e0-11e6-8272-38ceb4577af6.gif)

any tips on keeping the boxes next to each-other? 
( [my source](https://github.com/Rolograaf/elm-orderingcode) )

**Comment by mdgriffith** [comment]
I can take a look, but I'm not sure how you're compiling/running your Elm code(i.e. the index file doesn't seem to import any js).  Maybe I'm missing something.

The style containing alignTop should be the container element.

**Comment by Rolograaf** [comment]
Sorry about that. This is my first project using [create-elm-app](https://github.com/halfzebra/create-elm-app) which I wanted to try out. Not sure if I like it, maybe too much magic happening and the tests do not work for me on Win10.

Anyway -- with this bootstrapping/scaffolding utility -- I watch during development with globally (locally) installed `elm-app start` and deploy to dist with `elm-app build`. So this will not be of much use for someone else to check the source out.

But then I thought to upload the dist and now I can inspect it in my browser. If you want to have a look it is at http://rolograaf.nl/elm/ . This is better for continuing my CSS debugging. But if you have a tip, I would be grateful.

I know the style should be on container, but apparently you can use `align-self flex-start` on the item to overrule the container. ( What I understand from the [flexbox-playground](https://demos.scotch.io/visual-guide-to-css3-flexbox-flexbox-playground/demos/))

**Comment by mdgriffith** [comment]
I don't see align-self in your code, but you shouldn't need it. 

The only advise I can give would be to

 * set `flowLeft` on your main container
 * remove `inline` from dropdown container

That should do it

**Comment by mdgriffith** [comment]
I'm closing this issue because I don't see a clear example of an issue with the library.   If you do find an issue and can reduce it down to a [short, self contained, correct example](http://sscce.org/), feel free to create a new issue!

(and thanks for using the library :D)
