### ISSUE TITLE
Using `auto` for `Length`

### ISSUE THREAD

**Issue by mpizenberg** [mdgriffith/style-elements#43]
Hi, I was tinkering with the grids but even before trying some responsive stuff, I got stuck by an "incoherent" size behavior. I've done a very simple layout ([example on Ellie][ellie]) which can be summurized by this code:

[ellie]: https://ellie-app.com/3My3PrVNLKfa1/0

```elm
myGridLayout : NamedGrid
myGridLayout =
    { columns = [ fill 1 ]
    , rows =
        [ ( fill 1, [ spanAll "header" ] )
        , ( fill 1, [ spanAll "title" ] )
        , ( fill 1, [ spanAll "tags" ] )
        , ( fill 1, [ spanAll "text" ] )
        ]
    }


myGridElements : List (NamedOnGrid (Element Styles var msg))
myGridElements =
    [ named "header" imageHeader
    , named "title" pageTitle
    , named "tags" tags
    , named "text" textContent
    ]
```

The issue when using the `fill 1` is that every cell is stretched. I would like that each row takes just the amount needed. This is exactly what we obtain if lengths are manually set to `auto`. In Firefox, I get the same behavior by using `fill 0`. However, in Chromium the image header go beyond (lower) what it should, leaking down to the title area.

So I wondered if you have any idea of how to fix this without the `auto` keyword, my CSS Fu beeing pretty low. If not, is `auto` implementable according to you?

PS: I am aware that flexbox is more appropriate for 1 column but it was just supposed to be the mobile first design.

**Comment by mdgriffith** [comment]
`auto` is exposed as `content` in v4.0.0.  I really appreciate the issue, thanks!

**Comment by mpizenberg** [comment]
Thanks a lot! I really like your approach for layout and will happily give
it another try at 4.0.
