### ISSUE TITLE
Style.Background.imageWith src property not including url functional notation in generated css

### ISSUE THREAD

**Issue by jonathanfishbein1** [mdgriffith/style-elements#44]
>  BackgroundImage
            [ Style.Background.imageWith <|
                { src = "EarthBanner.jpg"
                , position = ( 0, 0 )
                , repeat = Style.Background.noRepeat
                }
            ]

generates

> .background-image__2888595622
{
  border-style: solid;
  background-image: EarthBanner.jpg;
  background-repeat: no-repeat;
  background-position: 0px 0px;
}

**Comment by mdgriffith** [comment]
I believe this was addressed at some point.  Sorry for such a delay in commenting here, I'm planning on keeping the issues more up to date in the future :)
