### ISSUE TITLE
Add equivalent of `Html.Lazy`

### ISSUE THREAD

**Issue by zakvdm** [mdgriffith/style-elements#51]
Hi

I have been using (and enjoying!) this library in an app that displays a large list of items. I need to dynamically update items in the list when they're clicked, etc. Unfortunately, these updates are currently pretty slow and a look at the browser performance tab seems to show that my app is spending a lot of time in my `view` function.

I don't have any experience with performance optimization in Elm, but it sounds like [Html.Lazy](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Lazy) could help a lot with my use case. Is this something that should have an equivalent version in `style-elements`?

**Comment by popara** [comment]
I have hit the same issue today, having a list of 100 elements that render rather deep tree of elements. 

My solution was dirty as Muddy Water Blues: make proxy function, and wrap and unwrap Html data structure. 

```haskell 
import Html exposing (Html)
import Html.Lazy as Lazy 

bigitems : List A -> Element S V Msg
bigitems = 
 (Lazy.lazy biHtml) >> html 

biHtml : List A -> Html Msg
biHtml = 
  bigItemsView >> toHtml spreadsheet  

bigItemsView : List A -> Element S V Msg
bigItemsView list = 
--   ... actual view function for that big list ...


```

It works rather nice. That one iteration takes about 250ms (which is a lot), but it's only once, not on each frame :D

**Comment by mdgriffith** [comment]
This will be incoming in `v5`!
