### ISSUE TITLE
when and whenJust behave like map, but the arguments are flipped

### ISSUE THREAD

**Issue by BrianHicks** [mdgriffith/style-elements#63]
(persisting from Slack)

odd usage report: `when` and `whenJust` act like mapping functions but take the collection first instead of last. I'd expect it to be, for example, `whenJust : (a -> El) -> Maybe a -> El`

**Comment by opsb** [comment]
For constructing views I find this ordering really useful. As html is a tree structure it feels natural for the code to also be nested. Some examples from my codebase:

```
editProfileDrawer context model =
    whenJust model.editProfile <|
        \editProfile ->
            Element.map EditProfileMsg <|
                EditProfile.view context editProfile
```

```
whenJust (Attachment.findSummary attachments) <|
    \suggestion ->
        paragraph Styles.None
            [ spacing 10 ]
            [ suggestedTitleLabel
            , suggestedTitle suggestion
            , when (isTextValid suggestion) <|
                el Styles.SuggestedTitleLink [ Events.onClick <| SwitchToSuggestedTitle suggestion ] (text "use this instead")
            ]
```
```
when viewConfig.showFeedPicker <|
    DropdownPicker.view
        dropdownConfig
        []
        conversationEditor.feed
        conversationEditor.feedPicker     
```

**Comment by mdgriffith** [comment]
Some other thoughts beyond Oliver's example (which was definitely the idea when I made them this way):

  * It seems reasonable that `when` would match the order of an `if` expression.
  * If that is the case, having `whenJust` match `when` made sense
  * The "collection last" pattern is very nice for pipelines `|>`, though I don't think pipelines are very common in the view.  

Anyway, that was my thought process.  Of course, I'm open to other arguments if people can show how code would be improved if the arguments are flipped :)

**Comment by mdgriffith** [comment]
Sidenote, if things stay this way, this would probably be a good candidate for the FAQ/documentation website

**Comment by BrianHicks** [comment]
Ok, that makes sense! I wasn't looking at it in context. I agree this maybe should end up in the FAQ.

Note for future readers: if it *really* bothers you, try this:

```
withJust = flip Elements.withJust
```

Closing now, assuming WONTFIX.
