### ISSUE TITLE
Can't set type_ on inputText

### ISSUE THREAD

**Issue by dela3499** [mdgriffith/style-elements#64]
When [inputText is defined](https://github.com/mdgriffith/style-elements/blob/637852d494aff9d97d083cd4721de9f3ea0b9eb0/src/Element.elm#L709), the `type_` attribute is set to `text`. 

```elm
attrs = (Attr.type_ "text" :: Attr.value content :: attrs)
```
This seems to prevent the user from setting `type_` on their own. When I try providing `type_ "email"` in the attributes list, it doesn't seem to work. 

```elm
inputText None [ type_ "email" ] ""
```

Perhaps the first term of the attrs definition can simply be omitted, or left present only when `type_` isn't provided as an argument to inputText. 

```elm
attrs = (Attr.value content :: attrs)
```
Here's my current workaround. 

```elm
node "input" <|
    el None
        [ type_ "email"] 
        (text "")
```

**Comment by alvivi** [comment]
Same here. You cannot create a password input field (for example) with the current version. 😞

**Comment by dela3499** [comment]
@alvivi See the workaround. 

In your case: 

```elm
node "input" <|
    el None
        [ type_ "password"] 
        (text "")
```

**Comment by popara** [comment]
http://package.elm-lang.org/packages/mdgriffith/style-elements/4.0.0/Element-Input#username 

In 4.0 this is fixed. 

Check it out.

**Comment by mdgriffith** [comment]
This was addressed in v4 :)
