### ISSUE TITLE
Cannot use keyed grids

### ISSUE THREAD

**Issue by MazeChaZer** [mdgriffith/style-elements#78]
Keyed grids expect a list of `OnGrid ( String, Element [...])`, but the `area` function only allows me to create values of the type `OnGrid (Element [...])`. Because `OnGrid` is an internal opaque type, I see no way to create the desired value.

Am I missing something obvious here?

- Elm: 0.18
- style-elements: 3.3.0

**Comment by mdgriffith** [comment]
Thanks for this!  Corrected in v4.0.0
