### ISSUE TITLE
"If you want to use something like em" then what?

### ISSUE THREAD

**Issue by drathier** [mdgriffith/style-elements#90]
Looks like some of the docs are missing. What's the rest of this sentence supposed to be?

https://github.com/mdgriffith/style-elements/blob/09d47724584454ffde1678c3971df3b7b1890857/examples/Basic.elm#L46

**Comment by mdgriffith** [comment]
Ha, oh boy.  I swear I need a spell checker for my doc comments.  Check out the [FAQ](https://github.com/mdgriffith/style-elements/blob/master/FAQ.md), it covers this :D

I'll update the docs  too, thanks!
