### ISSUE TITLE
Input.text not clearing from external event

### ISSUE THREAD

**Issue by tuxagon** [mdgriffith/style-elements#98]
Hello! I encountered an issue with `Input.text` and it could be isolated or a bigger issue. Ultimately, what I was trying to do was create a textbox and allow it to be cleared via some external action like a button click.

Here is a SSCCE of the problem https://ellie-app.com/b75NcBq9sa1/0

When I clicked the button, it did not clear. I presumed, since the `{ ... value : String ... }` field is just fed the value, that the text box would change, but it did not.

- Elm: 0.18
- style-elements: 4.1.0
- Browser: Firefox and Chrome
- Operating System: Ubuntu 17.04

Edit: It was mentioned in slack to use the `textKey` option, but the cursor started jumping out after every button press. It should be mentioned that the textbox cleared with that option, however.

Here is an updated SSCCE using `textKey` https://ellie-app.com/XPsQCptha1/0

This should probably be related to #91

**Comment by eniac314** [comment]
I think you need to update the counter in the ClearText branch, not in the EditText branch.
https://ellie-app.com/rtzcXCkH3a1/0

**Comment by tuxagon** [comment]
Ah, that was not obvious. Thanks!
